workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - test_dev:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - dev
      - test_stage:
          filters:
            branches:
              only: test
      - test_pre-prod:
          filters:
            branches:
              only: master
